[package]
name = "sched-callback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.1.1"
tokio = { version = "1.37.0", features = ["sync", "rt", "time", "macros"] }
